// front-end-react/src/views/recommend/index.js
import { useEffect, useState, memo } from 'react';
import Slider from '../../components/slider';
import Scroll from '../../components/scroll';
import { getRecommend } from '../../api';

function Recommend() {
  const [sliders, setSliders] = useState([]);
  const [albums, setAlbums] = useState([]);
  useEffect(() => {
    getRecommend().then((res) => {
      setSliders(res.sliders);
      setAlbums(res.albums);
    });
  }, []);
  return (
    <div className='recommend w-full overflow-scroll fixed bottom-0 top-20'>
      <Scroll>
        <div>
          <div className='slider-wrapper w-full h-0 overflow-hidden'>
            <div className='slider-content absolute top-0 left-0 w-full h-full'>
              <Slider sliders={sliders}></Slider>
            </div>
          </div>
          <div className='recommend-list'>
            <ul>
              {albums.map((item) => {
                return (
                  <li key={item.id}>
                    <div>
                      <img src={item.pic} alt='' width={60} height={60} />
                    </div>
                    <div className='text'>
                      <h2 className='name'>{item.username}</h2>
                      <p className='title'>{item.title}</p>
                    </div>
                  </li>
                );
              })}
            </ul>
          </div>
        </div>
      </Scroll>
    </div>
  );
}

export default memo(Recommend);

// front-end/src/views/recommend.vue
<template>
  <div class="recommend">
    <scroll class="recommend-content">
      <div>
        <div class="slider-wrapper">
          <div class="slider-content">
            <slide v-if="sliders.length" :sliders="sliders"></slide>
          </div>
        </div>
        <div class="recommend-list">
          <h1 class="list-title">热门歌单推荐</h1>
          <ul v-if="albums.length">
            <li v-for="item in albums" class="item" :key="item.id">
              <div class="icon">
                <img width="60" height="60" :src="item.pic" />
              </div>
              <div class="text">
                <h2 class="name">
                  {{ item.username }}
                </h2>
                <p class="title">
                  {{ item.title }}
                </p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </scroll>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import Slide from '@/components/slide/index.vue'
import Scroll from '@/components/scroll/index.vue'
import { getRecommend } from '@/api'

export default defineComponent({
  components: { Slide, Scroll },
  setup() {
    const sliders = ref([])
    const albums = ref([])

    getRecommend().then((res) => {
      sliders.value = res.sliders
      albums.value = res.albums
    })

    return {
      sliders,
      albums
    }
  }
})
</script>

<style lang="less" scoped>
.recommend {
  position: fixed;
  width: 100%;
  top: 88px;
  bottom: 0;
  overflow: scroll;
  .recommend-content {
    height: 100%;
    overflow: hidden;
    .slider-wrapper {
      position: relative;
      width: 100%;
      height: 0;
      padding-top: 40%;
      overflow: hidden;
      .slider-content {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
      }
    }
    .recommend-list {
      .list-title {
        height: 65px;
        line-height: 65px;
        text-align: center;
        font-size: @font-size-medium;
        color: @color-theme;
      }
      .item {
        display: flex;
        box-sizing: border-box;
        align-items: center;
        padding: 0 20px 20px 20px;
        .icon {
          flex: 0 0 60px;
          width: 60px;
          padding-right: 20px;
        }

        .text {
          display: flex;
          flex-direction: column;
          justify-content: center;
          flex: 1;
          line-height: 20px;
          overflow: hidden;
          font-size: @font-size-medium;
          .name {
            margin-bottom: 10px;
            color: @color-text;
          }
          .title {
            color: @color-text-d;
          }
        }
      }
    }
  }
}
</style>
