// front-end-react/src/components/player/index.js
import { FaHeart, FaRandom, FaExchangeAlt } from 'react-icons/fa'

function Player() {
  return (
    <div className="normal-player">
      <div className="top"></div>
      <div className="middle"></div>
      <div className="bottom">
        <div className="progress-bar"></div>
        <div className="operator">
          <div className="icon-left"></div>
          <div className="icon-left"></div>
          <div className="icon-center"></div>
          <div className="icon-right"></div>
          <div className="icon-right"></div>
        </div>
      </div>
    </div>
  )
}

export default Player

// front-end/src/components/player/index.vue
<template>
  <div class="player">
    <div class="normal-player">
      <div class="background">
        <img >
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  setup() {}
})
</script>

<style lang="less" scoped>
.player {
  .normal-player {
    position: fixed;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
  }
}
</style>
